### PR TITLE
Add floating button config

### PR DESCRIPTION
**Pull request by akshay196**
Floating button is easily accessible and always on top button that is
currently pointing to telegram group.

### CODE REVIEW

**Comment by akshay196** [comment]
@bhavin192 It looks like the [PR preview on Netlify](https://deploy-preview-157--pythonpune.netlify.app/) is not showing up the floating button even it is enabled in the config. Can you please confirm the preview is fetching the latest code from website-theme repo?

**Comment by bhavin192** [comment]
@akshay196 you will need to update the go.mod from this repository to point to latest website-theme. Try to run `hugo mod get -u github.com/python-pune/website-theme` and then `hugo mod tidy`

**Comment by akshay196** [comment]
> @akshay196 you will need to update the go.mod from this repository to point to latest website-theme. Try to run `hugo mod get -u github.com/pythonpune/website-theme` and then `hugo mod tidy`

Thanks. It helps. :)

**Comment by akshay196** [comment]
PR preview link: https://deploy-preview-157--pythonpune.netlify.app/

**Review by bhavin192 — APPROVED** [review]

**Pull request merged**
